# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Restaurant.ui'
#
# Created: Fri Dec 16 00:21:06 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(866, 670)
        self.customerTab = QtGui.QWidget()
        self.customerTab.setObjectName("customerTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.customerTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.customerTable = QtGui.QTableWidget(self.customerTab)
        self.customerTable.setObjectName("customerTable")
        self.customerTable.setColumnCount(8)
        self.customerTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.customerTable.setHorizontalHeaderItem(7, item)
        self.customerTable.horizontalHeader().setDefaultSectionSize(250)
        self.gridLayout_3.addWidget(self.customerTable, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.customerEditButton = QtGui.QPushButton(self.customerTab)
        self.customerEditButton.setObjectName("customerEditButton")
        self.horizontalLayout_5.addWidget(self.customerEditButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.addCustomerBtn = QtGui.QPushButton(self.customerTab)
        self.addCustomerBtn.setEnabled(False)
        self.addCustomerBtn.setObjectName("addCustomerBtn")
        self.horizontalLayout_9.addWidget(self.addCustomerBtn)
        self.deleteCustomerBtn = QtGui.QPushButton(self.customerTab)
        self.deleteCustomerBtn.setEnabled(False)
        self.deleteCustomerBtn.setObjectName("deleteCustomerBtn")
        self.horizontalLayout_9.addWidget(self.deleteCustomerBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        Form.addTab(self.customerTab, "")
        self.orderTab = QtGui.QWidget()
        self.orderTab.setObjectName("orderTab")
        self.gridLayout = QtGui.QGridLayout(self.orderTab)
        self.gridLayout.setObjectName("gridLayout")
        self.orderTable = QtGui.QTableWidget(self.orderTab)
        self.orderTable.setObjectName("orderTable")
        self.orderTable.setColumnCount(5)
        self.orderTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(4, item)
        self.orderTable.horizontalHeader().setDefaultSectionSize(250)
        self.gridLayout.addWidget(self.orderTable, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addOrderBtn = QtGui.QPushButton(self.orderTab)
        self.addOrderBtn.setEnabled(False)
        self.addOrderBtn.setObjectName("addOrderBtn")
        self.horizontalLayout_4.addWidget(self.addOrderBtn)
        self.deleteOrderBtn = QtGui.QPushButton(self.orderTab)
        self.deleteOrderBtn.setEnabled(False)
        self.deleteOrderBtn.setObjectName("deleteOrderBtn")
        self.horizontalLayout_4.addWidget(self.deleteOrderBtn)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.orderEditButton = QtGui.QPushButton(self.orderTab)
        self.orderEditButton.setObjectName("orderEditButton")
        self.horizontalLayout_6.addWidget(self.orderEditButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        Form.addTab(self.orderTab, "")
        self.menuTab = QtGui.QWidget()
        self.menuTab.setObjectName("menuTab")
        self.gridLayout_2 = QtGui.QGridLayout(self.menuTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.menuTable = QtGui.QTableWidget(self.menuTab)
        self.menuTable.setObjectName("menuTable")
        self.menuTable.setColumnCount(2)
        self.menuTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.menuTable.setHorizontalHeaderItem(1, item)
        self.menuTable.horizontalHeader().setDefaultSectionSize(400)
        self.menuTable.horizontalHeader().setMinimumSectionSize(60)
        self.menuTable.horizontalHeader().setStretchLastSection(False)
        self.horizontalLayout_7.addWidget(self.menuTable)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.menuEditButton = QtGui.QPushButton(self.menuTab)
        self.menuEditButton.setObjectName("menuEditButton")
        self.horizontalLayout_8.addWidget(self.menuEditButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addItemBtn = QtGui.QPushButton(self.menuTab)
        self.addItemBtn.setObjectName("addItemBtn")
        self.horizontalLayout_3.addWidget(self.addItemBtn)
        self.deleteItemBtn = QtGui.QPushButton(self.menuTab)
        self.deleteItemBtn.setObjectName("deleteItemBtn")
        self.horizontalLayout_3.addWidget(self.deleteItemBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        Form.addTab(self.menuTab, "")
        self.statisticsTab = QtGui.QWidget()
        self.statisticsTab.setObjectName("statisticsTab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.statisticsTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statisticsTable = QtGui.QTableWidget(self.statisticsTab)
        self.statisticsTable.setObjectName("statisticsTable")
        self.statisticsTable.setColumnCount(2)
        self.statisticsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.statisticsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.statisticsTable.setHorizontalHeaderItem(1, item)
        self.statisticsTable.horizontalHeader().setDefaultSectionSize(500)
        self.horizontalLayout.addWidget(self.statisticsTable)
        Form.addTab(self.statisticsTab, "")

        self.retranslateUi(Form)
        Form.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "TabWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.customerTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customerTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customerTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.customerTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Phone", None, QtGui.QApplication.UnicodeUTF8))
        self.customerTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.customerTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Orders Made", None, QtGui.QApplication.UnicodeUTF8))
        self.customerTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "Total Orders", None, QtGui.QApplication.UnicodeUTF8))
        self.customerTable.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Form", "Total Money Spent", None, QtGui.QApplication.UnicodeUTF8))
        self.customerEditButton.setText(QtGui.QApplication.translate("Form", "Enable Editing", None, QtGui.QApplication.UnicodeUTF8))
        self.addCustomerBtn.setText(QtGui.QApplication.translate("Form", "Add Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCustomerBtn.setText(QtGui.QApplication.translate("Form", "Delete Customer", None, QtGui.QApplication.UnicodeUTF8))
        Form.setTabText(Form.indexOf(self.customerTab), QtGui.QApplication.translate("Form", "Customers", None, QtGui.QApplication.UnicodeUTF8))
        self.orderTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Order Number", None, QtGui.QApplication.UnicodeUTF8))
        self.orderTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.orderTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.orderTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Items", None, QtGui.QApplication.UnicodeUTF8))
        self.orderTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.addOrderBtn.setText(QtGui.QApplication.translate("Form", "Add Order", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteOrderBtn.setText(QtGui.QApplication.translate("Form", "Delete Order", None, QtGui.QApplication.UnicodeUTF8))
        self.orderEditButton.setText(QtGui.QApplication.translate("Form", "Enable Editing", None, QtGui.QApplication.UnicodeUTF8))
        Form.setTabText(Form.indexOf(self.orderTab), QtGui.QApplication.translate("Form", "Orders", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Menu Item", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEditButton.setText(QtGui.QApplication.translate("Form", "Enable Editing", None, QtGui.QApplication.UnicodeUTF8))
        self.addItemBtn.setText(QtGui.QApplication.translate("Form", "Add Item", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteItemBtn.setText(QtGui.QApplication.translate("Form", "Delete Item", None, QtGui.QApplication.UnicodeUTF8))
        Form.setTabText(Form.indexOf(self.menuTab), QtGui.QApplication.translate("Form", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticsTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Value", None, QtGui.QApplication.UnicodeUTF8))
        Form.setTabText(Form.indexOf(self.statisticsTab), QtGui.QApplication.translate("Form", "Statistics", None, QtGui.QApplication.UnicodeUTF8))

